# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fleetctl < Formula
  desc "Fleet management CLI tool for edge device orchestration"
  homepage "https://fleetd.sh"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fleetd-sh/fleetd/releases/download/v0.0.1/fleetctl_0.0.1_darwin_amd64.tar.gz"
      sha256 "36ce27d9320b9296fb4059aa8a4c95466c58d0e0671454155392eeef7f5a6da1"

      def install
        bin.install "fleetctl"

        # Install bash completions
        output = Utils.safe_popen_read("#{bin}/fleetctl", "completion", "bash")
        (bash_completion/"fleetctl").write output

        # Install zsh completions
        output = Utils.safe_popen_read("#{bin}/fleetctl", "completion", "zsh")
        (zsh_completion/"_fleetctl").write output

        # Install fish completions
        output = Utils.safe_popen_read("#{bin}/fleetctl", "completion", "fish")
        (fish_completion/"fleetctl.fish").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fleetd-sh/fleetd/releases/download/v0.0.1/fleetctl_0.0.1_darwin_arm64.tar.gz"
      sha256 "a6ab460677dd19723b68e1426df73b4cc9ddc0f7f4c2a5d0df7da66126d8aa53"

      def install
        bin.install "fleetctl"

        # Install bash completions
        output = Utils.safe_popen_read("#{bin}/fleetctl", "completion", "bash")
        (bash_completion/"fleetctl").write output

        # Install zsh completions
        output = Utils.safe_popen_read("#{bin}/fleetctl", "completion", "zsh")
        (zsh_completion/"_fleetctl").write output

        # Install fish completions
        output = Utils.safe_popen_read("#{bin}/fleetctl", "completion", "fish")
        (fish_completion/"fleetctl.fish").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fleetd-sh/fleetd/releases/download/v0.0.1/fleetctl_0.0.1_linux_amd64.tar.gz"
      sha256 "276d0970e645b5ade80f0f5490e88ec0ba9c75ab5b649402707615e8d9895eed"
      def install
        bin.install "fleetctl"

        # Install bash completions
        output = Utils.safe_popen_read("#{bin}/fleetctl", "completion", "bash")
        (bash_completion/"fleetctl").write output

        # Install zsh completions
        output = Utils.safe_popen_read("#{bin}/fleetctl", "completion", "zsh")
        (zsh_completion/"_fleetctl").write output

        # Install fish completions
        output = Utils.safe_popen_read("#{bin}/fleetctl", "completion", "fish")
        (fish_completion/"fleetctl.fish").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fleetd-sh/fleetd/releases/download/v0.0.1/fleetctl_0.0.1_linux_arm64.tar.gz"
      sha256 "139d4876d474319975c8914b8fa6f0bf18b34c23095c10758a692ba7e187fa31"
      def install
        bin.install "fleetctl"

        # Install bash completions
        output = Utils.safe_popen_read("#{bin}/fleetctl", "completion", "bash")
        (bash_completion/"fleetctl").write output

        # Install zsh completions
        output = Utils.safe_popen_read("#{bin}/fleetctl", "completion", "zsh")
        (zsh_completion/"_fleetctl").write output

        # Install fish completions
        output = Utils.safe_popen_read("#{bin}/fleetctl", "completion", "fish")
        (fish_completion/"fleetctl.fish").write output
      end
    end
  end

  test do
    system "#{bin}/fleetctl", "--version"
  end
end
